### ISSUE TITLE
Diff_mustache error in regulator function

### ISSUE THREAD

**Issue by batzza** [ay-lab/mustache#29] opened 2021-11-11 21:08 UTC
In the latest version of diff_mustache, I receive the following fatal error:

```
There is no contact in chrmosome 21 to work on.
Traceback (most recent call last):
  File "Tools/mustache/mustache/diff_mustache.py", line 1342, in <module>
    main()
  File "Tools/mustache/mustache/diff_mustache.py", line 1270, in main
    o = regulator(f1, f2, args.norm_method, CHRM_SIZE, args.outdir,
  File "Tools/mustache/mustache/diff_mustache.py", line 1044, in regulator
    x2, y2, v2 = read_hic_file(f2, norm_method, CHRM_SIZE, distance_in_bp, chromosome,chromosome2, res)
ValueError: too many values to unpack (expected 3)
```

I thought the issue might have be at line 474 where the function read_hic_file returns 4 values instead of 3 if len(val)==0

```
if len(val)==0:
        print(f'There is no contact in chrmosome {chr1} to work on.')
        return [],[],[],res
    else:
        val[np.isnan(val)] = 0
```
I tried manually removing ",res" from line 474. After this change, the error at line 1044 in regulator is fixed but I get the following error and the program does not complete the run:

```
There is no contact in chrmosome 21 to work on.
Normalizing contact map...
Traceback (most recent call last):
  File "Tools/mustache/mustache/diff_mustache.py", line 1342, in <module>
    main()
  File "Tools/mustache/mustache/diff_mustache.py", line 1270, in main
    o = regulator(f1, f2, args.norm_method, CHRM_SIZE, args.outdir,
  File "Tools/mustache/mustache/diff_mustache.py", line 1063, in regulator
    n2 = max(max(x2), max(y2)) + 1
ValueError: max() arg is an empty sequence
```

**Comment by roayaei** [comment] 2021-11-11 22:08
Yep, the problem is that the chr21 of your second contact map is empty. Please update. Hopefully, it is fixed now (I haven't tested it on an actual empty chromosome).

**Comment by batzza** [comment] 2021-11-11 22:14
I'll try the fix and report back but the contact map is not empty at chr21.

Here's the first hic file in juicebox:
![image](https://user-images.githubusercontent.com/53917879/141376320-884387cf-dbf9-45a1-bf4b-4c443bced53c.png)


and here's the second:
![image](https://user-images.githubusercontent.com/53917879/141376350-fa12901c-e9ee-4a12-9ab5-a281d378d547.png)


This chr is a bit sparse but it definitely has contacts (although perhaps the contacts are filtered out by this script?)

**Comment by roayaei** [comment] 2021-11-11 22:24
I see, but for some reason mustache doesn't read any contact. Do you get any loop by mustache on those chromosomes?

**Comment by batzza** [comment] 2021-11-12 16:42
Updated version finished without error. But you are right, I just checked and no loops called on Chr21 of that second file. hmm.... any idea why?

**Comment by ay-lab** [comment] 2021-11-12 18:16
Can you share the data. I'd be happy to take a look (abbas@lji.org).

**Comment by ay-lab** [comment] 2021-11-12 19:51
Also, I would check the normalization values for chromosome 21. Can juicebox show the normalized contact maps for chromosome 21 (is that what you are showing above)?

**Closed** 2022-05-02 06:40 UTC
